version: "3"
services:
  app:
    container_name: "stackhead-test"
    build:
      context: Dockerfiles
      dockerfile: single-container.Dockerfile
    ports:
    - 32773:8080
    links:
    - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example