version: "3"
services:
  app:
    container_name: "mackerel-test"
    build:
      context: .
    ports:
    - 32773:8080
    links:
    - db
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example